apiVersion: v1
kind: List
items:
- apiVersion: networkop.co.uk/v1beta1
  kind: Topology
  metadata:
    name: r20
    namespace: 2ceos
  spec:
    links:
    - uid: 1
      peer_pod: r2
      local_intf: eth1
      peer_intf: eth3
      local_ip: 12.12.12.1/24
      peer_ip: 12.12.12.2/24
- apiVersion: v1
  kind: Pod
  metadata:
    name: r20
    namespace: 2ceos
    labels:
      test: 2node
  spec: 
    containers: 
    - image: docker.io/vrnetlab/vr-csr:17.03.06
      name: pod
      securityContext:
        privileged: true 
      command: ["/launch.py"]
- apiVersion: v1
  kind: Service
  metadata:
    name: service-r20
    namespace: 2ceos
  spec:
    selector:
      test: 2node
    ports:
    - protocol: TCP
      port: 22
      targetPort: 22
    type: LoadBalancer