---
apiVersion: v1
kind: List
items:
- apiVersion: networkop.co.uk/v1beta1
  kind: Topology
  metadata:
    name: r20
    namespace: 10-xrv9k
  spec:
    links:
    - uid: 1
      peer_pod: r2
      local_intf: eth1
      peer_intf: eth3
      local_ip: 12.12.12.1/24
      peer_ip: 12.12.12.2/24
- apiVersion: v1
  kind: Pod
  metadata:
    name: r20
    labels:
      test: 2node
  spec: 
    containers: 
    - image: alpine
      name: pod
      command:  ["/bin/sh", "-c", "sleep 2000000000000"]